feat: reworked algorithm calculation of withdrawal frame validators
lidofinance/withdrawals-api pull request #251
Opened 2024-09-19 09:07 UTC by Tarens2

### Description

- updated calculation validators withdraw time

### Demo

### Code review notes

### Testing notes

### Checklist:

- [ ] Checked the changes locally.
- [ ] Created / updated analytics events.
- [ ] Created / updated the technical documentation (README.md / [docs](https://docs.lido.fi/) / etc.).
- [ ] Affects / requires changes in other services (Matomo / Sentry / CloudFlare / etc.).

2024-09-23 13:58 UTC, DiRaiks commented on src/common/execution-provider/execution-provider.service.ts
> +    const provider = new ethers.JsonRpcProvider(this.configService.get('EL_RPC_URLS')[0]);
With this implementation, the functionality of fallbacks and logging is lost. "SimpleFallbackJsonRpcBatchProvider" doesn't fit here? Maybe you can still use it and there is only a typing problem?

2024-09-23 14:00 UTC, DiRaiks commented on src/jobs/validators/utils/get-validator-withdrawal-timestamp.ts
> +/*
👍

2024-09-23 14:06 UTC, DiRaiks commented on src/jobs/validators/utils/get-validator-withdrawal-timestamp.ts
> +import { SECONDS_PER_SLOT } from '../../../common/genesis-time';
Just 'common/genesis-time' ?

2024-09-24 10:49 UTC, TheDZhon requested changes
I believe the `how-estimation-works.md` file should include these changes too

2024-09-24 10:52 UTC, TheDZhon commented on src/jobs/validators/utils/get-validator-withdrawal-timestamp.ts
> +1. cursor goes from 0 to last validator index in queue
```suggestion
1. withdrawals sweep cursor goes from 0 to last validator index in queue
```

2024-09-24 15:20 UTC, Tarens2 commented on src/jobs/validators/utils/get-validator-withdrawal-timestamp.ts
> +1. cursor goes from 0 to last validator index in queue
fixed

2024-09-24 20:35 UTC, DiRaiks approved these changes

2024-09-25 16:15 UTC, TheDZhon approved these changes
:shipit:

2024-09-26 08:14 UTC, merged